/* AUTO-GENERATED by tools/emit_event_h.py: Map001 ev37 pg0 (rotten meat).
 * Do not hand-edit. Jumps from converted/baked/jumps.json. */
static const FhCmd DEMO_EV[] = {
  {101,0,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {401,0,21,0,{0,0,0,0,0,0,0,0,0,0},"Awful smell comes from all the rotten meat on "},
  {401,0,21,0,{0,0,0,0,0,0,0,0,0,0},"the table! Plates are covered with maggots."},
  {101,0,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {401,0,21,0,{0,0,0,0,0,0,0,0,0,0},"It does make you wonder if someone actually eats this"},
  {401,0,21,0,{0,0,0,0,0,0,0,0,0,0},"stuff. After all, why have them here otherwise?"},
  {102,0,21,0,{0,0,0,0,0,0,0,0,0,0},"Take some\nLeave it"},
  {402,0,17,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {101,1,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {401,1,21,0,{0,0,0,0,0,0,0,0,0,0},"You take some \\c[2]Rotten meat\\c[0] with you."},
  {401,1,21,0,{0,0,0,0,0,0,0,0,0,0},"It's soft and squishy, barely able to hold together."},
  {230,1,21,0,{20,0,0,0,0,0,0,0,0,0},NULL},
  {101,1,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {401,1,21,0,{0,0,0,0,0,0,0,0,0,0},"One of the maggots runs up your arm."},
  {126,1,21,0,{21,0,0,1,0,0,0,0,0,0},NULL},
  {123,1,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {0,1,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {402,0,19,0,{1,0,0,0,0,0,0,0,0,0},NULL},
  {0,1,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {404,0,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
  {0,0,21,0,{0,0,0,0,0,0,0,0,0,0},NULL},
};
static const int DEMO_EV_LEN = 21;
