#!/usr/bin/env python3
"""Bake battle database slice: classes, enemies, skills, troops.

Source: Fear & Hunger/www/data/{Classes,Enemies,Skills,Troops}.json
(owned copy). Trait math follows rpg_objects.js exactly:
  xparam (hit/eva/...) = traitsSum (additive, base 0)
  sparam/param-rate (pdr/mdr/grd/elements) = traitsPi (base 1.0)
Attack element defaults to 1 when no TRAIT_ATTACK_ELEMENT (31) exists.
Skill bytecode comes from converted/code/formulas.bin at runtime
(only metadata is baked here).

Usage (from repo root):
    python3 tools/bake_battle_db.py --out psp/gu_demo/battle_db.h
"""
import argparse
import json
import pathlib
import sys


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='psp/gu_demo/battle_db.h')
    args = ap.parse_args()

    game = pathlib.Path('Fear & Hunger_WIN/www/data')
    classes = json.load(open(game / 'Classes.json', encoding='utf-8'))
    troops = json.load(open(game / 'Troops.json', encoding='utf-8'))

    L = ['/* AUTO-GENERATED by tools/bake_battle_db.py. Do not hand-edit. */',
         '/* Class level tables: params[param][level-1], levels 1..100. */']
    for cid in (1, 5, 6, 7):
        c = next(x for x in classes if x and x['id'] == cid)
        L.append(f'/* {cid} {c["name"]} */')
        for p in range(8):
            vals = [int(v) for v in c['params'][p][:100]]
            rows = []
            for i in range(0, 100, 20):
                rows.append(','.join(str(v) for v in vals[i:i + 20]))
            L.append(f'static const unsigned short CLS{cid}_P{p}[100] = {{')
            L += [f'    {r},' for r in rows]
            L.append('};')
        L.append(f'static const int CLS{cid}_EXP[4] = '
                 f'{{{",".join(str(v) for v in c["expParams"])}}};')
    L.append('/* Troop exp/gold rewards (id, exp, gold). */')
    L.append('static const struct { int id, exp, gold; } TROOP_RW[] = {')
    for t in troops:
        if not t:
            continue
        L.append(f'    {{{t["id"]},{t.get("exp") or 0},{t.get("gold") or 0}}},')
    L.append('    {0,0,0},');
    L.append('};')

    enemies = json.load(open(game / 'Enemies.json', encoding='utf-8'))
    skills = json.load(open(game / 'Skills.json', encoding='utf-8'))

    def tsum(ts, code, did):
        return sum(t['value'] for t in ts if t['code'] == code and
                   t['dataId'] == did)

    def tpi(ts, code, did):
        r = 1.0
        for t in ts:
            if t['code'] == code and t['dataId'] == did:
                r *= t['value']
        return r

    def tfirst(ts, code):
        for t in ts:
            if t['code'] == code:
                return t['dataId']
        return 1

    L.append('/* Enemies (id, mhp, atk, def, mat, mdf, agi, luk, exp, gold,'
             ' elem, hit, eva, erate[8], art, w, h, tw, th, stride). */')
    L.append('static const struct { int id, mhp, atk, def, mat, mdf, agi,'
             ' luk, exp, gold, elem; double hit, eva, er[8];'
             ' const char *name, *art; int w, h, tw, th, stride; }'
             ' FOE_DB[] = {')
    for x in enemies:
        if not x:
            continue
        ts = x.get('traits', [])
        p = x['params']
        er = [tpi(ts, 11, e) for e in range(8)]
        art = x.get('battlerName', '')
        aw = ah = atw = ath = ast = 0
        mp = pathlib.Path(f'converted/enemies/{art}.meta.json')
        if mp.exists():
            m = json.loads(mp.read_text())
            aw, ah, atw, ath, ast = (m['w'], m['h'], m['tex_w'], m['tex_h'],
                                    m['tex_w'])
        nm = x['name'].replace('"', '')
        L.append(
            f'    {{{x["id"]},{p[0]},{p[2]},{p[3]},{p[4]},{p[5]},{p[6]},'
            f'{p[7]},{x.get("exp") or 0},{x.get("gold") or 0},'
            f'{tfirst(ts, 31)},{tsum(ts, 22, 0):g},{tsum(ts, 22, 1):g},'
            f'{{{",".join(f"{v:g}" for v in er)}}},'
            f'"{nm}","{art}",{aw},{ah},{atw},{ath},{ast}}},')
    L.append('};')

    L.append('/* Enemy AI (foe id, skill, rating, ctype, cp1, cp2). */')
    L.append('static const struct { int foe, skill, rating, ctype, cp1, cp2; }'
             ' FOE_AI[] = {')
    for x in enemies:
        if not x:
            continue
        for a in x.get('actions', []):
            L.append(f'    {{{x["id"]},{a["skillId"]},{a["rating"]},'
                     f'{a["conditionType"]},{a.get("conditionParam1") or 0},'
                     f'{a.get("conditionParam2") or 0}}},')
    L.append('    {0},');
    L.append('};')

    L.append('/* Skills (id, hitType, scope, speed, variance, element,'
             ' dmgType, crit). Bytecode loads from formulas.bin. */')
    L.append('static const struct { int id, hit, scope, speed, var, elem,'
             ' type, crit; } SKILL_DB[] = {')
    for x in skills:
        if not x:
            continue
        d = x.get('damage', {})
        L.append(f'    {{{x["id"]},{x.get("hitType", 0)},{x.get("scope", 0)},'
                 f'{x.get("speed", 0)},{d.get("variance", 0)},'
                 f'{d.get("elementId", 0)},{d.get("type", 0)},'
                 f'{1 if d.get("critical") else 0}}},')
    L.append('    {0},');
    L.append('};')

    L.append('/* Troop members (troop, enemy, x, y). */')
    L.append('static const struct { int troop, foe, x, y; } TROOP_MB[] = {')
    for t in troops:
        if not t:
            continue
        for m in t.get('members', []):
            if m.get('enemyId', 0) > 0:
                L.append(f'    {{{t["id"]},{m["enemyId"]},{m["x"]},{m["y"]}}},')
    L.append('    {0,0,0,0},');
    L.append('};')

    weapons = json.load(open(game / 'Weapons.json', encoding='utf-8'))
    armors = json.load(open(game / 'Armors.json', encoding='utf-8'))
    actors = json.load(open(game / 'Actors.json', encoding='utf-8'))

    def equip_params(equips):
        plus = [0] * 8
        xt = {}
        er = {}
        elem = 1
        for slot, eid in enumerate(equips):
            if not eid:
                continue
            src = weapons if slot == 0 else armors
            it = next((v for v in src if v and v['id'] == eid), None)
            if not it:
                continue
            for p in range(8):
                plus[p] += it.get('params', [0] * 8)[p]
            for t in it.get('traits', []):
                if t['code'] == 22:
                    xt[t['dataId']] = xt.get(t['dataId'], 0.0) + t['value']
                elif t['code'] == 11:
                    er[t['dataId']] = er.get(t['dataId'], 1.0) * t['value']
                elif t['code'] == 31 and slot == 0:
                    elem = t['dataId']
        return plus, xt, er, elem

    L.append('/* Actors resolved (id, level, mhp, mmp, atk, def, mat, mdf,'
             ' agi, luk, elem, exp_cur, hit, eva, cri, erate[8]). */')
    L.append('static const struct { int id, level, mhp, mmp, atk, def, mat,'
             ' mdf, agi, luk, elem, exp; double hit, eva, cri, er[8]; }'
             ' ACTOR_DB[] = {')
    for x in actors:
        if not x:
            continue
        cl = next(v for v in classes if v and v['id'] == x['classId'])
        lv = x.get('initialLevel', 1)
        eb, ee, ea, ed = cl['expParams']
        exp_cur = round(eb * (lv - 1) ** (0.9 + ea / 250.0) * lv * (lv + 1) /
                        (6 + ed) + (lv - 1) * ee) if lv > 1 else 0
        plus, xt, er, elem = equip_params(x.get('equips', []))
        cxt = {}
        for t in cl.get('traits', []):
            if t['code'] == 22:
                cxt[t['dataId']] = cxt.get(t['dataId'], 0.0) + t['value']
        hit = cxt.get(0, 0.0) + xt.get(0, 0.0)
        eva = cxt.get(1, 0.0) + xt.get(1, 0.0)
        cri = cxt.get(2, 0.0) + xt.get(2, 0.0)
        stats = [cl['params'][p][lv - 1] + plus[p] for p in range(8)]
        er8 = [er.get(e, 1.0) for e in range(8)]
        L.append(
            f'    {{{x["id"]},{lv},{stats[0]},{stats[1]},{stats[2]},'
            f'{stats[3]},{stats[4]},{stats[5]},{stats[6]},{stats[7]},'
            f'{elem},{exp_cur},{hit:g},{eva:g},{cri:g},'
            f'{{{",".join(f"{v:g}" for v in er8)}}}}},')
    L.append('    {0},');
    L.append('};')
    out = pathlib.Path(args.out)
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out}')


if __name__ == '__main__':
    sys.exit(main())
