#!/usr/bin/env python3
"""Bake the battle database (classes, enemies, skills, items, troops, actors) to a C header."""
import argparse
import json
import pathlib
import sys


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='psp/gu_demo/battle_db.h')
    args = ap.parse_args()

    game = pathlib.Path('Fear & Hunger_WIN/www/data')
    classes = json.load(open(game / 'Classes.json', encoding='utf-8'))
    troops = json.load(open(game / 'Troops.json', encoding='utf-8'))

    L = ['/* AUTO-GENERATED by tools/bake_battle_db.py. Do not hand-edit. */']
    for cid in (1, 5, 6, 7):
        c = next(x for x in classes if x and x['id'] == cid)
        for p in range(8):
            vals = [int(v) for v in c['params'][p][:100]]
            rows = []
            for i in range(0, 100, 20):
                rows.append(','.join(str(v) for v in vals[i:i + 20]))
            L.append(f'static const unsigned short CLS{cid}_P{p}[100] = {{')
            L += [f'    {r},' for r in rows]
            L.append('};')
        L.append(f'static const int CLS{cid}_EXP[4] = '
                 f'{{{",".join(str(v) for v in c["expParams"])}}};')
    L.append('static const struct { int id, exp, gold; } TROOP_RW[] = {')
    for t in troops:
        if not t:
            continue
        L.append(f'    {{{t["id"]},{t.get("exp") or 0},{t.get("gold") or 0}}},')
    L.append('    {0,0,0},');
    L.append('};')

    enemies = json.load(open(game / 'Enemies.json', encoding='utf-8'))
    skills = json.load(open(game / 'Skills.json', encoding='utf-8'))

    def tsum(ts, code, did):
        return sum(t['value'] for t in ts if t['code'] == code and
                   t['dataId'] == did)

    def tpi(ts, code, did):
        r = 1.0
        for t in ts:
            if t['code'] == code and t['dataId'] == did:
                r *= t['value']
        return r

    def tfirst(ts, code):
        for t in ts:
            if t['code'] == code:
                return t['dataId']
        return 1

    L.append('static const struct { int id, mhp, atk, def, mat, mdf, agi,'
             ' luk, exp, gold, elem; double hit, eva, er[8];'
             ' const char *name, *art; int w, h, tw, th, stride; }'
             ' FOE_DB[] = {')
    for x in enemies:
        if not x:
            continue
        ts = x.get('traits', [])
        p = x['params']
        er = [tpi(ts, 11, e) for e in range(8)]
        art = x.get('battlerName', '')
        aw = ah = atw = ath = ast = 0
        mp = pathlib.Path(f'converted/enemies/{art}.meta.json')
        if mp.exists():
            m = json.loads(mp.read_text())
            aw, ah, atw, ath, ast = (m['w'], m['h'], m['tex_w'], m['tex_h'],
                                    m['tex_w'])
        nm = x['name'].replace('"', '')
        L.append(
            f'    {{{x["id"]},{p[0]},{p[2]},{p[3]},{p[4]},{p[5]},{p[6]},'
            f'{p[7]},{x.get("exp") or 0},{x.get("gold") or 0},'
            f'{tfirst(ts, 31)},{tsum(ts, 22, 0):g},{tsum(ts, 22, 1):g},'
            f'{{{",".join(f"{v:g}" for v in er)}}},'
            f'"{nm}","{art}",{aw},{ah},{atw},{ath},{ast}}},')
    L.append('};')

    L.append('static const struct { int foe, skill, rating, ctype, cp1, cp2; }'
             ' FOE_AI[] = {')
    for x in enemies:
        if not x:
            continue
        for a in x.get('actions', []):
            L.append(f'    {{{x["id"]},{a["skillId"]},{a["rating"]},'
                     f'{a["conditionType"]},{a.get("conditionParam1") or 0},'
                     f'{a.get("conditionParam2") or 0}}},')
    L.append('    {0},');
    L.append('};')

    L.append('static const struct { int id, hit, scope, speed, var, elem,'
              ' type, crit, succ, occ, stype, mp, reps, anim, icon; char nm[40]; char msg[48]; } SKILL_DB[] = {')
    for x in skills:
        if not x:
            continue
        d = x.get('damage', {})
        L.append(f'    {{{x["id"]},{x.get("hitType", 0)},{x.get("scope", 0)},'
                  f'{x.get("speed", 0)},{d.get("variance", 0)},'
                  f'{d.get("elementId", 0)},{d.get("type", 0)},'
                  f'{1 if d.get("critical") else 0},'
                  f'{x.get("successRate", 100)},{x.get("occasion", 0)},'
                  f'{x.get("stypeId", 0)},{x.get("mpCost", 0)},'
                  f'{x.get("repeats", 1)},{x.get("animationId", -1)},'
                  f'{x.get("iconIndex", 0)},"{x.get("name", "")[:39]}",'
                  f'"{x.get("message1", "")[:47]}"}},')
    L.append('    {0},');
    L.append('};')

    def fxrows(owner, items):
        rows = []
        for x in items:
            if not x:
                continue
            for e in x.get('effects', []) or []:
                v1 = e.get('value1', 0)
                v2 = e.get('value2', 0)
                v1s = f'{float(v1):g}' if isinstance(v1, float) else str(int(v1) if isinstance(v1, (int, float)) else 0)
                rows.append((x['id'], e.get('code', 0), e.get('dataId', 0),
                             v1s, int(v2) if isinstance(v2, (int, float)) else 0))
        return rows

    L.append('static const struct { int id, code, data; double v1; int v2; }'
             ' SKILL_FX[] = {')
    for r in fxrows(0, skills):
        L.append(f'    {{{r[0]},{r[1]},{r[2]},{r[3]},{r[4]}}},')
    L.append('    {0,0,0,0,0},');
    L.append('};')

    items = json.load(open(game / 'Items.json', encoding='utf-8'))
    L.append('static const struct { int id, hit, scope, speed, var, elem,'
             ' type, succ, occ, cons, price, reps, icon; char nm[40]; } ITEM_DB[] = {')
    for x in items:
        if not x:
            continue
        d = x.get('damage', {})
        L.append(f'    {{{x["id"]},{x.get("hitType", 0)},{x.get("scope", 0)},'
                  f'{x.get("speed", 0)},{d.get("variance", 0)},'
                  f'{d.get("elementId", 0)},{d.get("type", 0)},'
                  f'{x.get("successRate", 100)},{x.get("occasion", 0)},'
                  f'{1 if x.get("consumable") else 0},{x.get("price", 0)},'
                  f'{x.get("repeats", 1)},{x.get("iconIndex", 0)},"{x.get("name", "")[:39]}"}},')
    L.append('    {0},');
    L.append('};')
    L.append('static const struct { int id, code, data; double v1; int v2; }'
             ' ITEM_FX[] = {')
    for r in fxrows(1, items):
        L.append(f'    {{{r[0]},{r[1]},{r[2]},{r[3]},{r[4]}}},')
    L.append('    {0,0,0,0,0},');
    L.append('};')

    L.append('static const struct { int cls, lv, sk; } CLASS_LEARN[] = {')
    for c in classes:
        if not c:
            continue
        for lr in c.get('learnings', []) or []:
            L.append(f'    {{{c["id"]},{lr.get("level", 1)},{lr.get("skillId", 0)}}},')
    L.append('    {0,0,0},');
    L.append('};')

    L.append('static const struct { int troop, foe, x, y; } TROOP_MB[] = {')
    for t in troops:
        if not t:
            continue
        for m in t.get('members', []):
            if m.get('enemyId', 0) > 0:
                L.append(f'    {{{t["id"]},{m["enemyId"]},{m["x"]},{m["y"]}}},')
    L.append('    {0,0,0,0},');
    L.append('};')

    weapons = json.load(open(game / 'Weapons.json', encoding='utf-8'))
    armors = json.load(open(game / 'Armors.json', encoding='utf-8'))
    actors = json.load(open(game / 'Actors.json', encoding='utf-8'))

    def equip_params(equips):
        plus = [0] * 8
        xt = {}
        er = {}
        elem = 1
        for slot, eid in enumerate(equips):
            if not eid:
                continue
            src = weapons if slot == 0 else armors
            it = next((v for v in src if v and v['id'] == eid), None)
            if not it:
                continue
            for p in range(8):
                plus[p] += it.get('params', [0] * 8)[p]
            for t in it.get('traits', []):
                if t['code'] == 22:
                    xt[t['dataId']] = xt.get(t['dataId'], 0.0) + t['value']
                elif t['code'] == 11:
                    er[t['dataId']] = er.get(t['dataId'], 1.0) * t['value']
                elif t['code'] == 31 and slot == 0:
                    elem = t['dataId']
        return plus, xt, er, elem

    L.append('static const struct { int id, level, mhp, mmp, atk, def, mat,'
             ' mdf, agi, luk, elem, exp; double hit, eva, cri, er[8]; }'
             ' ACTOR_DB[] = {')
    for x in actors:
        if not x:
            continue
        cl = next(v for v in classes if v and v['id'] == x['classId'])
        lv = x.get('initialLevel', 1)
        eb, ee, ea, ed = cl['expParams']
        exp_cur = round(eb * (lv - 1) ** (0.9 + ea / 250.0) * lv * (lv + 1) /
                        (6 + ed) + (lv - 1) * ee) if lv > 1 else 0
        plus, xt, er, elem = equip_params(x.get('equips', []))
        cxt = {}
        for t in cl.get('traits', []):
            if t['code'] == 22:
                cxt[t['dataId']] = cxt.get(t['dataId'], 0.0) + t['value']
        hit = cxt.get(0, 0.0) + xt.get(0, 0.0)
        eva = cxt.get(1, 0.0) + xt.get(1, 0.0)
        cri = cxt.get(2, 0.0) + xt.get(2, 0.0)
        stats = [cl['params'][p][lv - 1] + plus[p] for p in range(8)]
        er8 = [er.get(e, 1.0) for e in range(8)]
        L.append(
            f'    {{{x["id"]},{lv},{stats[0]},{stats[1]},{stats[2]},'
            f'{stats[3]},{stats[4]},{stats[5]},{stats[6]},{stats[7]},'
            f'{elem},{exp_cur},{hit:g},{eva:g},{cri:g},'
            f'{{{",".join(f"{v:g}" for v in er8)}}}}},')
    L.append('    {0},');
    L.append('};')
    L.append('static const struct { int weap, st; } WEAPON_ATKST[] = {')
    for x in weapons:
        if not x:
            continue
        for t in x.get('traits', []) or []:
            if t.get('code') == 32:
                L.append(f'    {{{x["id"]},{t.get("dataId", 0)}}},')
    L.append('    {0,0},');
    L.append('};')
    L.append('static const struct { int st, icon; } STATE_ICON[] = {')
    states = json.load(open(game / 'States.json', encoding='utf-8'))
    for x in states:
        if not x:
            continue
        L.append(f'    {{{x["id"]},{x.get("iconIndex", 0)}}},')
    L.append('    {0,0},');
    L.append('};')
    L.append('static const struct { int id; char nm[32]; } ACTOR_NAMES[] = {')
    for x in actors:
        if not x:
            continue
        L.append(f'    {{{x["id"]},"{x.get("name", "")[:31]}"}},')
    L.append('    {0,""},');
    L.append('};')
    L.append('static const struct { const char *name; int w, h, tw, th,'
             ' stride; } BACK_DB[] = {')
    for cat in ('battlebacks1', 'battlebacks2'):
        cdir = pathlib.Path(f'converted/{cat}')
        if not cdir.exists():
            continue
        for mp in sorted(cdir.glob('*.meta.json')):
            try:
                m = json.loads(mp.read_text())
                base = mp.name[:-len('.meta.json')]
                L.append(f'    {{"{base}",{m["w"]},{m["h"]},'
                         f'{m["tex_w"]},{m["tex_h"]},{m["tex_w"]}}},')
            except (KeyError, ValueError):
                continue
    L.append('    {0,0,0,0,0,0},');
    L.append('};')
    out = pathlib.Path(args.out)
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out}')


if __name__ == '__main__':
    sys.exit(main())
