#!/usr/bin/env python3.12
"""Embed one real event list as a C array for the EBOOT message demo.

Covers exactly the codes in Map001 ev37 pg0 (rotten-meat table):
101/401/102/402/404/0/230/126/123. Jumps from converted/baked/jumps.json.
For other codes this emitter refuses (keeps the demo honest).

Usage:
    python3.12 tools/emit_event_h.py "Fear & Hunger_WIN/www" --out psp/gu_demo/event_demo.h
"""
import json, sys, pathlib

def cstr(s):
    out = ['"']
    for b in s.encode('utf-8'):
        ch = chr(b)
        if ch == '"': out.append('\\"')
        elif ch == '\\': out.append('\\\\')
        elif ch == '\n': out.append('\\n')
        elif 32 <= b < 127: out.append(ch)
        else: out.append(f'\\x{b:02x}')
    out.append('"')
    return ''.join(out)

def main():
    game = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[sys.argv.index('--out') + 1])
    data = game / 'data'
    d = json.loads((data / 'Map001.json').read_text(encoding='utf-8'))
    ev = next(e for e in d['events'] if e and e['id'] == 37)
    lst = ev['pages'][0]['list']
    jumps = json.loads(pathlib.Path('converted/baked/jumps.json').read_text())['jumps']
    jm = jumps.get('Map001.json/ev37/pg0', {})
    n = len(lst)
    L = ['/* AUTO-GENERATED by tools/emit_event_h.py: Map001 ev37 pg0 (rotten meat).',
         ' * Do not hand-edit. Jumps from converted/baked/jumps.json. */',
         'static const FhCmd DEMO_EV[] = {']
    for i, c in enumerate(lst):
        code = c.get('code', -1)
        assert code in (0, 101, 401, 102, 402, 404, 230, 126, 123), f'code {code} not covered'
        p = c.get('parameters', [])
        op, pp, s = 0, [0] * 10, 'NULL'
        if code in (401,) and p: s = cstr(str(p[0]))
        elif code == 102 and p: s = cstr('\n'.join(str(x) for x in p[0]))
        elif code == 402 and p: pp[0] = int(p[0])
        elif code == 230 and p: pp[0] = int(p[0])
        elif code == 126 and len(p) >= 4:
            pp = [int(p[0]), 0, int(p[2]), int(p[3]) if not isinstance(p[3], str) else 0] + [0] * 6
        elif code == 123 and len(p) >= 2:
            pp[0] = 'ABCD'.index(p[0]) if p[0] in 'ABCD' else 0
            pp[1] = int(p[1])
        L.append(f'  {{{code},{c.get("indent", 0)},{int(jm.get(str(i), n))},{op},'
                 f'{{{",".join(map(str, pp))}}},{s}}},')
    L += ['};', f'static const int DEMO_EV_LEN = {n};']
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out} ({n} cmds)')

if __name__ == '__main__':
    main()
