#!/usr/bin/env python3
"""Embed real event lists as C arrays for the EBOOT.

Generalized from the Map001-ev37 original: takes --map/--ev/--pg/--symbol
quadruples (repeatable) plus the legacy single-event form. Covers the codes
the runtime implements for these lists:
  0/101/401/102/402/404/411/111(types 0,1,8)/121/123/126/127/230/356.
Jumps from converted/baked/jumps.json (key 'Map.json/ev{id}/pg{pg}').
Other codes are refused (keeps the demo honest).

Usage:
    python3 tools/emit_event_h.py "Fear & Hunger_WIN/www" --out psp/gu_demo/event_demo.h
    # optional: --ev Map001 37 0 DEMO_EV --ev Map030 213 0 M30_EV213 ...
    # (defaults embed the historical set below)
"""
import json
import sys
import pathlib

DEFAULT_EVS = [
    ('Map030', 213, 0, 'M30_EV213'),
    ('Map030', 20, 0, 'M30_EV020'),
]

COVERED = (0, 101, 401, 102, 402, 404, 411, 412, 111, 121, 123, 126, 127,
           230, 356)


def cstr(s):
    out = ['"']
    for b in s.encode('utf-8'):
        ch = chr(b)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        elif 32 <= b < 127:
            out.append(ch)
        else:
            out.append(f'\\x{b:02x}')
    out.append('"')
    return ''.join(out)


def emit_one(game, baked_jumps, map_name, ev_id, pg, sym):
    data = game / 'data'
    d = json.loads((data / f'{map_name}.json').read_text(encoding='utf-8'))
    ev = next(e for e in d['events'] if e and e['id'] == ev_id)
    lst = ev['pages'][pg]['list']
    jm = baked_jumps.get(f'{map_name}.json/ev{ev_id}/pg{pg}', {})
    n = len(lst)
    L = [f'static const FhCmd {sym}[] = {{']
    for i, c in enumerate(lst):
        code = c.get('code', -1)
        assert code in COVERED, f'{sym}[{i}]: code {code} not covered'
        p = c.get('parameters', [])
        op, pp, s = 0, [0] * 10, 'NULL'

        def num(k, default=0):
            v = p[k] if len(p) > k and isinstance(p[k], (int, float)) else default
            return int(v)

        if code == 401 and p:
            s = cstr(str(p[0]))
        elif code == 101 and p:
            # params: [faceName, faceIndex, background, position]
            pp = [num(1), num(2), num(3)] + [0] * 7
            s = cstr(str(p[0]))
        elif code == 102 and p:
            s = cstr('\n'.join(str(x) for x in p[0]))
        elif code == 402 and p:
            pp[0] = num(0)
        elif code == 230 and p:
            pp[0] = num(0)
        elif code == 111 and p:
            op = num(0)
            assert op in (0, 1, 8), f'{sym}[{i}]: 111 type {op} not covered'
            if op == 0:
                pp = [num(1), num(2)] + [0] * 8
            elif op == 1:
                pp = [num(1), num(2), num(3), num(4)] + [0] * 6
            else:
                pp = [num(1)] + [0] * 9
        elif code == 121 and len(p) >= 3:
            pp = [num(0), num(1), num(2)] + [0] * 7
        elif code in (126, 127) and len(p) >= 4:
            op = num(1)
            v = p[3]
            pp = [num(0), 0, num(2),
                  int(v) if isinstance(v, (int, float)) else 0] + [0] * 6
        elif code == 123 and len(p) >= 2:
            pp[0] = 'ABCD'.index(p[0]) if p[0] in 'ABCD' else 0
            pp[1] = num(1)
        elif code == 356 and p:
            s = cstr(str(p[0]))
        L.append(f'  {{{code},{c.get("indent", 0)},{int(jm.get(str(i), n))},{op},'
                 f'{{{",".join(map(str, pp))}}},{s}}},')
    L += ['};', f'static const int {sym}_LEN = {n};']
    return L, n


def main():
    game = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[sys.argv.index('--out') + 1])
    baked = json.loads(
        pathlib.Path('converted/baked/jumps.json').read_text())['jumps']
    evs = list(DEFAULT_EVS)
    if '--ev' in sys.argv:
        evs = []
        args = sys.argv[sys.argv.index('--ev') + 1:]
        # consumed in groups of 4 until next flag/--out
        while args and not args[0].startswith('--'):
            m, e, pg, sym = args[:4]
            args = args[4:]
            evs.append((m, int(e), int(pg), sym))
    L = ['/* AUTO-GENERATED by tools/emit_event_h.py.',
         ' * Do not hand-edit. Jumps from converted/baked/jumps.json. */']
    for (m, e, pg, sym) in evs:
        lines, n = emit_one(game, baked, m, e, pg, sym)
        L.append(f'/* {m} ev{e} pg{pg} ({n} cmds) */')
        L += lines
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out} ({len(evs)} events)')


if __name__ == '__main__':
    main()
