#!/usr/bin/env python3
"""Emit a map's Terrax event lights as a C table.

Reads Map<name>.json event note tags (light/fire/flashlight, same
parse as TerraxLighting.js) and writes map lights for the PSP mask
renderer. Flashlight cones and killswitches are skipped.
Conditional light ids stay as-is; the game flips them with Light
on/off plugin commands at runtime.

Usage (from repo root):
    python3 tools/emit_lights_h.py "Fear & Hunger_WIN/www" --map Map030 --out psp/gu_demo/map030_lights.h
"""
import json
import pathlib
import sys


def parse_note(note):
    parts = note.strip().split()
    if not parts:
        return None
    cmd = parts[0].lower()
    if cmd not in ('light', 'fire', 'flashlight'):
        return None
    if cmd == 'flashlight':
        return None
    flicker = 1 if cmd == 'fire' else 0
    rest = parts[1:]
    radius = 1
    if rest:
        try:
            radius = int(rest.pop(0))
        except ValueError:
            return None
    color = 0xffffff
    brightness = 0.0
    lightid = 0
    if rest and rest[0].startswith('#'):
        v = rest.pop(0)[1:]
        if len(v) == 3:
            v = v[0] * 2 + v[1] * 2 + v[2] * 2
        try:
            color = int(v, 16)
        except ValueError:
            color = 0xffffff
    for t in rest:
        if t[:1] in 'bB':
            try:
                brightness = int(t[1:]) / 100.0
            except ValueError:
                pass
        elif t.isdigit():
            lightid = int(t)
    return radius, color, brightness, flicker, lightid


def main() -> None:
    game = pathlib.Path(sys.argv[1])
    name = sys.argv[sys.argv.index('--map') + 1]
    out = pathlib.Path(sys.argv[sys.argv.index('--out') + 1])
    m = json.loads((game / 'data' / f'{name}.json').read_text(encoding='utf-8'))
    rows = []
    for e in m.get('events') or []:
        if not isinstance(e, dict):
            continue
        parsed = parse_note(e.get('note') or '')
        if parsed is None:
            continue
        r, c, b, f, lid = parsed
        rows.append((e['x'], e['y'], r, c, b, f, lid))
    sym = f'{name.upper()}_LIGHTS'
    L = ['/* AUTO-GENERATED by tools/emit_lights_h.py. Do not hand-edit. */',
         'static const MapLight ' + sym + '[] = {']
    for x, y, r, c, b, f, lid in rows:
        L.append(f'    {{{x}, {y}, {r}, 0x{c:06x}, {b:.1f}f, {f}, {lid}}},')
    L.append('};')
    L.append(f'static const int {name.upper()}_NLIGHTS = {len(rows)};')
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out} ({len(rows)} lights)')


if __name__ == '__main__':
    main()
