#!/usr/bin/env python3.12
"""Emit runtime/autotile_tables.h from converted/baked/autotiles.json."""
import json, pathlib

def main():
    auto = json.loads(pathlib.Path('converted/baked/autotiles.json').read_text())
    L = ['/* AUTO-GENERATED by tools/emit_autotile_h.py from rpg_core.js tables.',
         ' * FLOOR[48][4][2] WALL[16][4][2] WATERFALL[4][4][2]. Do not hand-edit. */',
         '#ifndef FH_AUTOTILE_TABLES_H', '#define FH_AUTOTILE_TABLES_H', '']
    for name, shape in (('FLOOR', 48), ('WALL', 16), ('WATERFALL', 4)):
        t = auto[name]
        assert len(t) == shape, (name, len(t))
        L.append(f'static const int FH_AUTO_{name}[{shape}][4][2] = {{')
        for row in t:
            L.append('  {' + ','.join(f'{{{a},{b}}}' for a, b in row) + '},')
        L.append('};')
    L += ['', '#endif']
    pathlib.Path('runtime/autotile_tables.h').write_text('\n'.join(L) + '\n')
    print('wrote runtime/autotile_tables.h')

if __name__ == '__main__':
    main()
