#!/usr/bin/env python3
"""Emit battle-animation frame and timing tables to a C header."""
import json
import sys
import pathlib


def cstr(s):
    out = ['"']
    for b in s.encode('utf-8'):
        ch = chr(b)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        elif 32 <= b < 127:
            out.append(ch)
        else:
            out.append(f'\\x{b:02x}')
    out.append('"')
    return ''.join(out)


ART_SHEETS = {'coin_flip', 'pinecone_pig', 'bloodsplurt', 'blood_shot',
              'bugs1', 'bugs2', 'slash1', 'needle_worm'}

TAIL_FRAMES = 6


def main():
    game = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[sys.argv.index('--out') + 1])
    anims = json.loads(
        (game / 'data/Animations.json').read_text(encoding='utf-8'))
    anims = sorted((a for a in anims if a), key=lambda a: int(a['id']))
    L = ['/* AUTO-GENERATED by tools/emit_anim_h.py. Do not hand-edit. */',
         'typedef struct { int pat, x, y, scale, rot, mir, opa, blend; }',
         '    FhAnimCell;',
         'typedef struct { int frame, scope, col[4], dur; const char *se; }',
         '    FhAnimTiming;']
    art_ids = set()
    holds = {}
    for a in anims:
        aid = int(a['id'])
        frames = a.get('frames') or []
        timings = a.get('timings') or []
        s1 = str(a.get('animation1Name') or '')
        s2 = str(a.get('animation2Name') or '')
        sheets = {s for s in (s1, s2) if s}
        has_art = bool(frames) and sheets <= ART_SHEETS
        if has_art:
            art_ids.add(aid)
            holds[aid] = len(frames)
        else:
            last = max((int(t.get('frame') or 0) for t in timings),
                       default=0)
            holds[aid] = max(last + TAIL_FRAMES, 1)
        if not has_art:
            continue
        cells = []
        coff = {}
        for fi, fr in enumerate(frames):
            coff[fi] = len(cells)
            for c in fr:
                cells.append((c[0], int(round(c[1] / 2)), int(round(c[2] / 2)),
                              int(c[3]), int(c[4]), int(c[5]), int(c[6]),
                              int(c[7])))
        L.append(f'static const FhAnimCell ANIM{aid}_CELLS[] = {{')
        for c in cells:
            L.append('    {%d,%d,%d,%d,%d,%d,%d,%d},' % c)
        L.append('};')
        nf = len(frames)
        L.append(f'static const int ANIM{aid}_FOFF[] = '
                 f'{{{",".join(str(coff[i]) for i in range(nf))},{len(cells)}}};')
    for a in anims:
        aid = int(a['id'])
        L.append(f'static const FhAnimTiming ANIM{aid}_TIM[] = {{')
        for t in a.get('timings', []):
            col = t.get('flashColor') or [0, 0, 0, 0]
            se = t.get('se')
            sen = se.get('name', '') if isinstance(se, dict) else ''
            L.append('    {%d,%d,{%d,%d,%d,%d},%d,%s},' % (
                int(t.get('frame') or 0), int(t.get('flashScope') or 0),
                int(col[0]), int(col[1]), int(col[2]), int(col[3]),
                int(t.get('flashDuration') or 0), cstr(sen)))
        L.append('};')
        L.append(f'static const int ANIM{aid}_NTIM = {len(a.get("timings", []))};')
    L.append('static const struct { int id; int pos, nframes, hold;')
    L.append('    const FhAnimCell *cells; const int *foff;')
    L.append('    const FhAnimTiming *tim; int ntim;')
    L.append('    const char *sheet1, *sheet2; } ANIM_IDX[] = {')
    for a in anims:
        aid = int(a['id'])
        if aid in art_ids:
            art = f'ANIM{aid}_CELLS, ANIM{aid}_FOFF, '
        else:
            art = '0, 0, '
        L.append(f'    {{{aid}, {int(a.get("position", 1))}, '
                 f'{len(a.get("frames") or [])}, {holds[aid]}, '
                 f'{art}'
                 f'ANIM{aid}_TIM, {len(a.get("timings", []))}, '
                 f'{cstr(str(a.get("animation1Name") or ""))}, '
                 f'{cstr(str(a.get("animation2Name") or ""))}}},')
    L.append('    {0},')
    L.append('};')
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out} ({len(anims)} anims, {len(art_ids)} with art)')


if __name__ == '__main__':
    sys.exit(main())
