#!/usr/bin/env python3
"""Bake battle-animation frames + timings for the PSP animation renderer.

Source: Fear & Hunger/www/data/Animations.json (owned copy). Cell offsets
are halved at bake time (world art is half-scale; scale%/rotation/opacity
are unit-free). Emits one header with per-animation frame/timing tables.

Cell (rpg_sprites.js Sprite_Animation.updateCellSprite):
  [pattern, x, y, scale%, rotationDeg, mirror, opacity, blendMode]
  pattern<0 hidden; <100 bitmap1 else bitmap2; 192px cells (96 baked).
Timing: [frame, flashScope (1 target, 2 screen, 3 hide), flashColor[4],
  flashDuration (x4 ticks), seName].

Usage (from repo root):
    python3 tools/emit_anim_h.py "Fear & Hunger_WIN/www" --out psp/gu_demo/anim_data.h
"""
import json
import sys
import pathlib


def cstr(s):
    out = ['"']
    for b in s.encode('utf-8'):
        ch = chr(b)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        elif 32 <= b < 127:
            out.append(ch)
        else:
            out.append(f'\\x{b:02x}')
    out.append('"')
    return ''.join(out)


ANIMS = [6, 7, 8, 12, 30, 95, 114, 126, 238, 266, 267, 268, 269]


def main():
    game = pathlib.Path(sys.argv[1])
    out = pathlib.Path(sys.argv[sys.argv.index('--out') + 1])
    anims = json.loads(
        (game / 'data/Animations.json').read_text(encoding='utf-8'))
    L = ['/* AUTO-GENERATED by tools/emit_anim_h.py. Do not hand-edit. */',
         'typedef struct { int pat, x, y, scale, rot, mir, opa, blend; }',
         '    FhAnimCell;',
         'typedef struct { int frame, scope, col[4], dur; const char *se; }',
         '    FhAnimTiming;']
    for aid in ANIMS:
        a = next(x for x in anims if x and x['id'] == aid)
        cells = []
        coff = {}
        for fi, fr in enumerate(a['frames']):
            coff[fi] = len(cells)
            for c in fr:

                cells.append((c[0], int(round(c[1] / 2)), int(round(c[2] / 2)),
                              int(c[3]), int(c[4]), int(c[5]), int(c[6]),
                              int(c[7])))
        L.append(f'static const FhAnimCell ANIM{aid}_CELLS[] = {{')
        for c in cells:
            L.append('    {%d,%d,%d,%d,%d,%d,%d,%d},' % c)
        L.append('};')
        nf = len(a['frames'])
        L.append(f'static const int ANIM{aid}_FOFF[] = '
                 f'{{{",".join(str(coff[i]) for i in range(nf))},{len(cells)}}};')
        L.append(f'static const FhAnimTiming ANIM{aid}_TIM[] = {{')
        for t in a.get('timings', []):
            col = t.get('flashColor') or [0, 0, 0, 0]
            se = t.get('se')
            sen = se.get('name', '') if isinstance(se, dict) else ''
            L.append('    {%d,%d,{%d,%d,%d,%d},%d,%s},' % (
                int(t.get('frame') or 0), int(t.get('flashScope') or 0),
                int(col[0]), int(col[1]), int(col[2]), int(col[3]),
                int(t.get('flashDuration') or 0), cstr(sen)))
        L.append('};')
        L.append(f'static const int ANIM{aid}_NTIM = {len(a.get("timings", []))};')
    L.append('static const struct { int id; int pos, nframes;')
    L.append('    const FhAnimCell *cells; const int *foff;')
    L.append('    const FhAnimTiming *tim; int ntim;')
    L.append('    const char *sheet1, *sheet2; } ANIM_IDX[] = {')
    for aid in ANIMS:
        a = next(x for x in anims if x and x['id'] == aid)
        L.append(f'    {{{aid}, {int(a.get("position", 1))}, {len(a["frames"])}, '
                 f'ANIM{aid}_CELLS, ANIM{aid}_FOFF, '
                 f'ANIM{aid}_TIM, {len(a.get("timings", []))}, '
                 f'{cstr(str(a.get("animation1Name") or ""))}, '
                 f'{cstr(str(a.get("animation2Name") or ""))}}},')
    L.append('    {0},')
    L.append('};')
    out.write_text('\n'.join(L) + '\n')
    print(f'wrote {out} ({len(ANIMS)} anims)')


if __name__ == '__main__':
    sys.exit(main())
